// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TzRsiQ8AfpRrEqQ0sRSIQxGHCTCm4uw',
    appId: '1:512598677574:web:2dc049a00368274fb49247',
    messagingSenderId: '512598677574',
    projectId: 'flutter-cc7a2',
    authDomain: 'flutter-cc7a2.firebaseapp.com',
    storageBucket: 'flutter-cc7a2.appspot.com',
    measurementId: 'G-23V0FBD6PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-HbqCPPjXiUcSLDputzxI_NkF3Yg-vI',
    appId: '1:512598677574:android:be85e94c97a9753bb49247',
    messagingSenderId: '512598677574',
    projectId: 'flutter-cc7a2',
    storageBucket: 'flutter-cc7a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYBqlDRr4KKZ3ec6k0XDj1uQcLnjOJks',
    appId: '1:832102315995:ios:b0b92524b2618274ad99fe',
    messagingSenderId: '832102315995',
    projectId: 'e-qurban-d985e',
    storageBucket: 'e-qurban-d985e.appspot.com',
    iosBundleId: 'com.example.eQurban',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYBqlDRr4KKZ3ec6k0XDj1uQcLnjOJks',
    appId: '1:832102315995:ios:b0b92524b2618274ad99fe',
    messagingSenderId: '832102315995',
    projectId: 'e-qurban-d985e',
    storageBucket: 'e-qurban-d985e.appspot.com',
    iosBundleId: 'com.example.eQurban',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_TzRsiQ8AfpRrEqQ0sRSIQxGHCTCm4uw',
    appId: '1:512598677574:web:807cab24e7e9f71eb49247',
    messagingSenderId: '512598677574',
    projectId: 'flutter-cc7a2',
    authDomain: 'flutter-cc7a2.firebaseapp.com',
    storageBucket: 'flutter-cc7a2.appspot.com',
    measurementId: 'G-9MJ0TCLV5H',
  );

}